environments:
  default:
  sandbox:

helmfiles:
- path: git::https://github.com/drequena/grafana-package.git@helmfile.yaml?ref=main
  values:
  - grafana:
      enabled: true
      resources:
        limits: 
          cpu: "100m"
- path: git::https://github.com/drequena/prometheus-package.git@helmfile.yaml?ref=main
  values:
  - prometheus:
      {{ .Values | get "prometheus" dict | toYaml | indent 6 | trim }}
